site_name: GrandLineX Project
site_url: https://grandlinex.github.io/docs
nav:
  - Home: index.md
  - Modules: modules.md
  - Utils: utils.md

theme:
  name: material
  logo: img/sq-black.png
  palette:
    primary: black
    accent: red
extra:
  homepage: https://github.com/grandlinex/
