site_name: GrandLineX Project
site_url: https://grandlinex.github.io/docs
nav:
  - Home: index.md
  - Concepts: concepts.md
  - Kernel Packages: kernel-packages.md
  - Bundles: bundles.md
  - Utils: utils.md

theme:
  name: material
  logo: img/sq-black.png
  palette:
    primary: black
    accent: red
extra:
  homepage: https://grandlinex.github.io/
